---
output:
  bookdown::pdf_document2:
      latex_engine: xelatex
      number_sections: false
      toc: false
mainfont: "Times New Roman"
geometry: margin = 1in
spacing: double
fontsize: 11pt
editor_options:
  markdown:
    wrap: sentence
bibliography: "supp_info_s6.bib"
csl: https://raw.githubusercontent.com/marlonecobos/kuenm/master/ecography.csl
link-citations: yes
header-includes:
   - \usepackage{lineno}
   - \linenumbers
   - \usepackage{setspace}\doublespacing
   - \usepackage{parskip}
   - \setlength{\parindent}{4em}
   - \setlength{\parskip}{0em}
---

```{r setup, include=FALSE}
library(ggplot2)
library(ggpubr)
library(phytools)
library(dplyr)
library(tidyr)
library(ks)
library(reshape2)
library(scales)

knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE,
                      fig.height = 5,
                      fig.width = 5,
                      fig.align = "center")

MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div <- readRDS("~/chapter-PaleoClimPoolCommDivPhyloStruct/R1/data/matrices/MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div.RDS")
```

### Study
### The historical and contemporary processes driving global phylogenetic structure – the case of bat communities/

### Supplementary Information 6

### Appendix S6. Raw data representation

```{r eval=TRUE, echo = FALSE, fig.align = "center", fig.height = 10, fig.width = 16.5, message=FALSE, warning=FALSE}
# Refactor data

MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$ID_Realm <- factor(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$ID_Realm,
                                                              levels = c(
                                                                "Neotropical",
                                                                "Nearctic",
                                                                "Afrotropical",
                                                                "Palearctic",
                                                                "Indomalay",
                                                                "Australasian"
                                                              )
)

MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$SamplingPool <- factor(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$SamplingPool,
                                                                  levels = c(
                                                                    "Global sampling",
                                                                    "Hemispheric sampling",
                                                                    "Realm sampling",
                                                                    "Plate sampling",
                                                                    "Biome sampling",
                                                                    "Ecoregion sampling"
                                                                  )
)

MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$ID_Biome <- as.factor(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$ID_Biome)

MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$ID_Biome_Acronym <- factor(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$ID_Biome,
                                                                      labels = abbreviate(gsub(
                                                                        "_",
                                                                        " ",
                                                                        levels(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$ID_Biome)
                                                                      )
                                                                      )
)
```


```{r fig_1, eval=TRUE, echo = FALSE, fig.align = "center", fig.height = 10, fig.width = 16.5, message=FALSE, warning=FALSE}
############################################################################ 
### Representing the phylogenetic community structure of bats across the ###
### gradient of sampling pool (or species pool) restriction              ###
############################################################################

# Representing NRI wrapping across Realms

NRI.Realm.boxplot <- ggplot(filter(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div,
                                   is.na(ID_Realm) == FALSE),
                            aes(x = SamplingPool, 
                                y = nri)
) +
  geom_jitter(aes(fill = SamplingPool, 
                  colour = SamplingPool), size = 0.01, alpha = 0.05) +
  geom_boxplot(aes(fill = SamplingPool), alpha = 0.7) +
  facet_wrap(~ID_Realm,
             nrow = 1,
             strip.position = "bottom"
  ) +
  ggsci::scale_fill_uchicago() +
  ggsci::scale_colour_uchicago() +
  # scale_fill_nord("baie_mouton", reverse = TRUE) +
  # scale_fill_okabeito(reverse = TRUE) +
  # scale_fill_brewer(palette = "Dark2") +
  # scale_fill_viridis(discrete = TRUE,
  #                    name="Sampling Pool") +
  scale_y_continuous(breaks = round(
    #pretty(MPD.LatLong.AllScales.rarefaction$NRI, n = 7)
    c(min(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$nri, na.rm = T),
      0,
      5,
      10,
      15,
      max(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$nri, na.rm = T))),
    limits = c(min(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$nri, na.rm = T) - 0.1,
               max(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$nri, na.rm = T) + 0.1)
  ) +
  geom_hline(yintercept = 0,
             alpha = 0.4) +
  labs(y="NRI", x = "") +
  theme_minimal() +
  theme_minimal(base_size = 20) +
  theme(strip.background = element_rect(fill = "white",
                                        linetype = NULL,
                                        color = "white"),
        strip.text = element_text(color = "black",
                                  face = "bold",
                                  size = 15),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 16, face="bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 16),
        legend.title.align = 0.5,
        legend.margin=margin(0, 0, 0, 0),
        legend.box.margin=margin(-5, -5, 2, -5)
  ) +   
  guides(fill = guide_legend(nrow = 1, 
                             byrow = TRUE,
                             title.position = "bottom",
                             title = "Lower  ⬅  Sampling Prame Restriction  ➡  Higher",)
  )

NTI.Realm.boxplot <- ggplot(filter(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div,
                                   is.na(ID_Realm) == FALSE),
                            aes(x = SamplingPool, y = nti)) +
  geom_jitter(aes(fill = SamplingPool, colour = SamplingPool), size = 0.01, alpha = 0.2) +
  geom_boxplot(aes(fill = SamplingPool), alpha = 0.7) +
  facet_wrap(~ID_Realm,
             nrow = 1,
             strip.position = "bottom"
  ) +
  ggsci::scale_fill_uchicago() +
  ggsci::scale_colour_uchicago() +
  scale_y_continuous(breaks = pretty(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$nti, n = 5),
                     # round(c(min(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$nti, na.rm = T),
                     #   0,
                     #   5,
                     #   10,
                     #   15,
                     #   max(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$nti, na.rm = T)))),
                     limits = c(min(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$nti, na.rm = T) - 0.1,
                                max(MPD.MNTD.LatLong.AllScales.raref.rel.worldClimate.diff.CWM.Div$nti, na.rm = T) + 0.1)
  ) +
  geom_hline(yintercept = 0,
             alpha = 0.4) +
  labs(y = "NTI", x = "") +
  theme_minimal(base_size = 20) +
  theme(strip.background = element_rect(fill = "white",
                                        linetype = NULL,
                                        color = "white"),
        strip.text = element_text(color = "black",
                                  face = "bold",
                                  size = 15),
        axis.text.y = element_text(face = "bold"),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 16, face="bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 15),
        legend.title.align = 0.5,
        legend.margin=margin(0, 0, 0, 0),
        legend.box.margin=margin(-5, -5, -5, -5)
  ) +
  guides(fill = guide_legend(nrow = 1, 
                             byrow = TRUE,
                             title.position = "bottom",
                             title = "Lower  ⬅  Sampling Frame Restriction  ➡  Higher",)
  )


### Combining plots into a single figure ###

(fig.NRI.NTI.Realm.boxplot <- ggarrange(
  NRI.Realm.boxplot +
    theme(axis.title.x = element_blank()), 
  NTI.Realm.boxplot,
  labels = c("A", "B"),
  ncol = 1, nrow = 2,
  widths = c(1, 1),
  heights = c(1, 1.1),
  align = "v",
  common.legend = TRUE,
  legend = "bottom")
)
```



